### ISSUE TITLE
Update caniusedb periodically

### ISSUE THREAD

**Issue by tomlankhorst** [jonrohan/browserl.ist#107]
Currently, data is provided by `caniuse-db 1.0.30000885`. Suggestion to update the caniusedb more regularly, automatically and periodically if possible. Use TravisCI?

**Comment by jonrohan** [comment]
Ah yes, I used to have a cron job on heroku that would update it, but forgot to add it when I upgraded to zeit

**Comment by tomlankhorst** [comment]
Great, thanks!

Op do 18 okt. 2018 om 18:41 schreef Jon Rohan <notifications@github.com>:

**Comment by krzysiek1507** [comment]
@jonrohan did you have a chance to set it up? It seems it doesn't deploy periodically.
