### ISSUE TITLE
Update to newest browserslist package version

### ISSUE THREAD

**Issue by fabb** [jonrohan/browserl.ist#108]
There was a bug in browserslist that was fixed recently, could you update to the newest version?

https://github.com/browserslist/browserslist/issues/320#issuecomment-441351076

**Comment by fabb** [comment]
Ok wait, the bug is not yet fixed in the newest browserslist release 4.3.4.

**Comment by msokk** [comment]
Nevertheless it would be good to get the latest browser releases in.
`package.json` has both caniuse db and browserslist specified as latest, so clean redeploy should be enough.

**Comment by msokk** [comment]
Ah, there used to be a cron job - #107

**Comment by fabb** [comment]
The fix was released in 4.3.5 just now, could you update the page now, or reenable the cron job?

**Comment by jonrohan** [comment]
yup, will fix now

**Comment by fabb** [comment]
Thanks!
