### ISSUE TITLE
Ability to add `in my stats`

### ISSUE THREAD

**Issue by jlamb1** [jonrohan/browserl.ist#110]
The [browserslist-ga tool](https://github.com/browserslist/browserslist-ga) can render a JSON file of percentage of browsers viewing a site according to GA. If we could upload that file and then reference `in my stats` in the search bar we could share specific stats to those less terminal-friendly.

Also this is a great tool, thanks!

**Comment by jonrohan** [comment]
That's a good idea, but I think it's out of scope for this site.
