### ISSUE TITLE
Unknown Browser Query `Node`

### ISSUE THREAD

**Issue by tyteen4a03** [jonrohan/browserl.ist#111]
This query fails: `node, last 2 years`

**Comment by jonrohan** [comment]
Currently an issue with [browserslist](http://github.com/browserslist/browserslist) will need to open an issue there.
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/54012/52369369-69d0b780-2a05-11e9-8fea-0ec9c7d57b40.png">

**Comment by tyteen4a03** [comment]
Done: https://github.com/browserslist/browserslist/issues/350
