### ISSUE TITLE
Regional stats broken

### ISSUE THREAD

**Issue by pmcelhaney** [jonrohan/browserl.ist#113]
When I enter "> 1%", I see Chrome 72 is at about 15%, which seems about right.

When I enter "> 1% in US", Chrome 72 is only at 1.04%. That doesn't seem right. According to [caniuse](https://raw.githubusercontent.com/Fyrd/caniuse/master/region-usage-json/US.json?at=e894906086e28), it should be 7.36%. 

When I enter "> 1% in CN", Chrome 72 is again at 1.04%. In fact, the stats for every browser are the same no matter which country is entered.

It seems something is awry with the regional stats.

**Comment by jpsc** [comment]
The same thing is happening when I reference '> 0.30% in NL' Android 4.3.3 does not show but I use >0.25 it does show and with 3% marketshare :)

**Comment by XhmikosR** [comment]
Could be because some packages are behind when deployment happens. @jonrohan does Zeit cache the node_modules?

Either way, now it seems it's fine

**Comment by jonrohan** [comment]
I think a lot of this is due to my struggles with keeping the dependencies updated. I think I have it working automatically now so shouldn't be a discrepancy going forward.
