### ISSUE TITLE
Missing icon for kaios

### ISSUE THREAD

**Issue by redeyes2015** [jonrohan/browserl.ist#114]
`https://browserl.ist/images/kaios.png` was not found for "KaiOS Browser2.5".

**Comment by XhmikosR** [comment]
Maybe open an issue on https://github.com/alrra/browser-logos/issues

While at it, it might be worth switching to the SVGs from the aforementioned repo @jonrohan

**Comment by XhmikosR** [comment]
If I find some time in the next days I will try to make use of the above package. It should at least be more modern with less files in the repo.

**Comment by XhmikosR** [comment]
I looked quickly into this and here's what I see. https://github.com/alrra/browser-logos is quite big, but let's assume this is not an issue.

The problem is that the browser names won't match the browser names that browserslist returns. So we'd need extra code to do this.

**Comment by jonrohan** [comment]
> I looked quickly into this and here's what I see. https://github.com/alrra/browser-logos is quite big, but let's assume this is not an issue.

Not a complete dealbreaker, assuming that there's no impact on the performance of the site.

> The problem is that the browser names won't match the browser names that browserslist returns. So we'd need extra code to do this.

This sucks, but as I see it. Pushing the work of keeping browser logos up to date to another package makes it worth the extra time translating the browser names. I've had a few of these issues where a logo was missing or not the current logo. I try to thing of the site as just a shell and a place to share urls for support.

**Comment by XhmikosR** [comment]
We'd need to keep a map of browser names and this can get too complicated :/

Unless you have something else on mind. I couldn't find any other solution so far.

**Comment by XhmikosR** [comment]
Also, do note that there's current no logo for Kaios in that package either. We could request it, and they add it, but IMO we shouldn't 404. Maybe show a placeholder logo if not found.

**Comment by alrra** [comment]
> I looked quickly into this and here's what I see. https://github.com/alrra/browser-logos is quite big, but let's assume this is not an issue.

The [browser logos](https://github.com/alrra/browser-logos) are available as separate packages on [`npm`](https://www.npmjs.com/org/browser-logos). They are usually keep up to date and highly optimized (e.g. see the changelogs for [`Firefox`](https://github.com/alrra/browser-logos/blob/b17e3e922072edf9dedaf17c4f8de63b375cb821/src/firefox/CHANGELOG.md#readme), [`Chrome`](https://github.com/alrra/browser-logos/blob/b17e3e922072edf9dedaf17c4f8de63b375cb821/src/chrome/CHANGELOG.md#readme), etc.).

> The problem is that the browser names won't match the browser names that browserslist returns. So we'd need extra code to do this.

Most projects (e.g.: [whatwg.org](https://github.com/whatwg/whatwg.org), [v8.dev](https://github.com/v8/v8.dev/), [ishoudinireadyyet.com](https://github.com/surma/ishoudinireadyyet.com), [browserosaurus](https://github.com/will-stone/browserosaurus), etc.), do that at build time.

> Pushing the work of keeping browser logos up to date to another package 

See: https://github.com/whatwg/whatwg.org/pull/265. :)
