### ISSUE TITLE
"> 2%" results shows browsers below 2%

### ISSUE THREAD

**Issue by jelmerdemaat** [jonrohan/browserl.ist#115]
Test: https://browserl.ist/?q=%3E2%25

Result:

![Screenshot 2019-06-05 at 09 50 48](https://user-images.githubusercontent.com/942560/58939466-94463d80-8777-11e9-9e72-8de40da442e9.png)

**Comment by tomm1996** [comment]
and `> 5%` hides browsers above 5%

https://browserl.ist/?q=%3E+2%25
![image](https://user-images.githubusercontent.com/4152001/60608837-a809b180-9dc0-11e9-8c33-b1cf67f1468c.png)

https://browserl.ist/?q=%3E+5%25
![image](https://user-images.githubusercontent.com/4152001/60608814-9fb17680-9dc0-11e9-8443-3589353a5ca8.png)

**Comment by jonrohan** [comment]
closing this because I can't reproduce it

**Comment by burtek** [comment]
https://github.com/browserslist/browserslist/issues/420
