### ISSUE TITLE
Server inaccessible

### ISSUE THREAD

**Issue by lol768** [jonrohan/browserl.ist#118]
>We can’t connect to the server at browsersl.ist.

**Comment by ThiefMaster** [comment]
Looks like DNS is broken for the domain

**Comment by jonrohan** [comment]
my bad, it should be back up

**Comment by ThiefMaster** [comment]
yep, works again! https://browsersl.ist/images/kaios.png 404s btw.

**Comment by jonrohan** [comment]
Does anyone have an image of kaios?
