### ISSUE TITLE
2 browsers with 0% in defaults

### ISSUE THREAD

**Issue by dmartinjs** [jonrohan/browserl.ist#125]
Why there is 2 browsers (Android Browser67, Baidu Browser7.12) with 0% usage into defaults query ?

<img width="1666" alt="62489853-209ccd00-b7c8-11e9-95f6-b0ebbe774a6b" src="https://user-images.githubusercontent.com/53537199/62572647-7dfe5000-b894-11e9-8154-eecaa2089080.png">

**Comment by stof** [comment]
probably because of `last 2 versions`

**Comment by XhmikosR** [comment]
The defaults have `not dead` so this shouldn't happen. Either way I believe this is unrelated to the site.

**Comment by stof** [comment]
these browsers are not considered dead in browserslist.

I think this is more about having `last 2 versions` in `defaults.

**Comment by XhmikosR** [comment]
Yeah, but again, this has nothing to do with the site :)

**Comment by jonrohan** [comment]
Closing this as an issue with browserslist
