### ISSUE TITLE
Latest browser versions out of date

### ISSUE THREAD

**Issue by edmorley** [jonrohan/browserl.ist#37]
Visiting http://browserl.ist/ and entering `last 1 versions` shows Firefox 49 and Chrome 53 as the latest versions, whereas the actual latest versions are 51 and 56 respectively.

Filing here rather than against https://github.com/Fyrd/caniuse , since http://caniuse.com does show the correct versions, so I'm presuming http://browserl.ist/ just doesn't have the latest data.json from them.

Many thanks :-)

**Comment by jonrohan** [comment]
Sorry I was slacking on updating the dependencies. Updated now!

**Comment by edmorley** [comment]
Many thanks :-)
