### ISSUE TITLE
Client-side only?

### ISSUE THREAD

**Issue by bfred-it** [jonrohan/browserl.ist#4]
Could this be moved to the client side so it can be easily cached, used offline, used instantly, and hosted on GitHub Pages?

**Comment by jonrohan** [comment]
If you're looking for something to lookup these without network, I recommend https://github.com/topaxi/browserslist-cli 

I'm not opposed to a fork doing a client-side only version. But the sole purpose of this site is to share via the internet a list of compatible browsers.
