### ISSUE TITLE
https version?

### ISSUE THREAD

**Issue by bfred-it** [jonrohan/browserl.ist#41]
SSL certificates are handled automatically by heroku if it's a paid plan, otherwise it looks like you can set up Let's Encrypt or you could put it behind CloudFlare.

**Comment by jonrohan** [comment]
I'd be interested in porting this over to https://zeit.co/now but haven't had the spare time to do that. On now https will just work™

**Comment by bfred-it** [comment]
Good idea!

**Comment by Splaktar** [comment]
It would be pretty easy to get this up on Firebase Hosting as well. They will provision your TLS cert for free. It's very painless and they also provide some good CLI tools for deploying, plus options for rollback.

**Comment by jonrohan** [comment]
Shipped https://browserl.ist/
