### ISSUE TITLE
ChromeAndroid version is always 57

### ISSUE THREAD

**Issue by ruedap** [jonrohan/browserl.ist#49]
Is this correct?
http://browserl.ist/?q=ChromeAndroid+%3E%3D+30
http://browserl.ist/?q=ChromeAndroid+%3E%3D+58

When Chrome, I think it is correct.
http://browserl.ist/?q=Chrome+%3E%3D+30

**Comment by jonrohan** [comment]
```
~ 7s
❯ browserslist -v
browserslist 2.1.4
                                                                                
~
❯ browserslist "ChromeAndroid >= 30"
and_chr 59
```

That's what I'm getting from the [browserslist](https://github.com/ai/browserslist) client. I would suggest [opening an issue](https://github.com/ai/browserslist/issues/new) there if you think something is wrong.
