### ISSUE TITLE
Support not in query 

### ISSUE THREAD

**Issue by stephenbe** [jonrohan/browserl.ist#51]
As stated in the docs : 
>not ie <= 8: exclude browsers selected before by previous queries. You can add not to any query.

This query does not seem to work.
http://browserl.ist/?q=not+IE+10

It should show all browser but IE 10

**Comment by benkeen** [comment]
Also "or" doesn't seem to be supported.

**Comment by awkaiser** [comment]
Feature requests related to core Browserslist implementation belong [on that project](https://github.com/ai/browserslist).

Also, use of `not` requires a preceding query, e.g. [`since 2015, not < 1%`](http://browserl.ist/?q=since+2015%2C+not+%3C+1%25):

> BrowserslistError: Write Any Browsers Query (For Instance, `Defaults`) Before `Not < 1%`
