### ISSUE TITLE
Doesn’t support multiline lists

### ISSUE THREAD

**Issue by sapegin** [jonrohan/browserl.ist#55]
My `browserslist` looks like this:

```
last 2 Chrome versions
last 2 Opera versions
last 2 Firefox versions
Safari > 10
```

When I paste it into an input, a browser replaces all the `\n` with spaces and I have an error:

```
BrowserslistError: Unknown Browser Query `Last 2 Chrome Versions Last 2 Opera Versions Last 2 Firefox Versions Safari > 10`
```

**Comment by leidegre** [comment]
I've tried various inputs, && || even tried changing the `input` to `textarea` to submit newlines, you're really going to be interested in the intersection of these queries.

**Comment by leidegre** [comment]
Actually, the handler sort of does, see here

https://github.com/jonrohan/browserl.ist/blob/a6b8fe30a01a519d03ed61cb0d741b3f538e6849/routes/index.js#L11

You can create an array by passing the query parameter `q` more than once, that's how express actually changes the `q` param to an array which the `browserlist` JavaScript API understands. The only caveat is that the input query gets JSONed into an array that you cannot submit.

For example,

http://browserl.ist/?q=last+2+versions&q=not%20IE%2010

**Comment by niksy** [comment]
Any chance of getting this supported? I think most of the Browserslist usage examples are using multiline lists and having support to copy/paste that list into textarea and submitting it would be great.

**Comment by lethak** [comment]
I second that
