### ISSUE TITLE
Query bug

### ISSUE THREAD

**Issue by frlinw** [jonrohan/browserl.ist#82]
http://browserl.ist/?q=%3E1%25
`> 1%` => edge 16: 0.75% is returned

**Comment by awkaiser** [comment]
The `browserl.ist` website [passes your query directly to `browserslist`](https://github.com/jonrohan/browserl.ist/blob/99f7b3afe91903ea5eb5ac75b4ba25c3e90de3f1/routes/index.js#L35), so I'd expect this to be an issue [for that project](https://github.com/ai/browserslist/issues) or possibly the underlying `caniuse` data. 🤔

**Comment by awkaiser** [comment]
# Live website

![screen shot 2018-02-16 at 6 08 00 pm](https://user-images.githubusercontent.com/155798/36337122-6072f60e-1344-11e8-9f10-be1995252b48.png)

# Local: `master` + freshly installed node_modules

![screen shot 2018-02-16 at 6 07 28 pm](https://user-images.githubusercontent.com/155798/36337125-67888c10-1344-11e8-8e99-8b3546a05fbb.png)

----

Huh! 🤔 @jonrohan, may want to try deploying a fresh install?

**Comment by jonrohan** [comment]
Site is updated and I hope is more automatic on keeping up to date now.
