### ISSUE TITLE
Does not support `node` version queries

### ISSUE THREAD

**Issue by code0100fun** [jonrohan/browserl.ist#99]
Browserslist 4.0.0 seems to have introduced some new [queries](https://github.com/browserslist/browserslist/blob/master/CHANGELOG.md#400-erinaceus-amurensis) that are unsupported (`maintained node versions`). Any query like `node <N>` results in a `Internal Server Error`.

**Comment by alex996** [comment]
Same issue here. Any update on this?

**Comment by jonrohan** [comment]
I haven't gotten a chance to debug it, if anyone has some extra time would be appreciated 🙏
